"""Reconstruct yuv_galosh_core.c with correct galosh_yuv_denoise + standalone harness."""
import os
import sys

SRC = os.path.expanduser(r'~\denoise_eval\standalone\yuv_galosh_core.c')

with open(SRC, 'rb') as f:
    raw = f.read()

# The first 'int galosh_yuv_denoise(' is the REAL one (at ~45288).
# Everything before it is correct (gamma helpers etc).
PREFIX_END = raw.find(b'int galosh_yuv_denoise(')
assert PREFIX_END > 0, f"function not found"

prefix = raw[:PREFIX_END]
print(f"PREFIX_END={PREFIX_END}, prefix ends: {repr(raw[PREFIX_END-30:PREFIX_END])}")

NL = b'\r\n'
def ln(*args):
    return b''.join(args) + NL

# ---- New galosh_yuv_denoise ----
FUNC = b''.join([
    ln(b'int galosh_yuv_denoise('),
    ln(b'        float *y_out, float *u_out, float *v_out,'),
    ln(b'        const float *y_in, const float *u_in, const float *v_in,'),
    ln(b'        const int width, const int height,'),
    ln(b'        const float * const *mc_y,'),
    ln(b'        const float * const *mc_u,'),
    ln(b'        const float * const *mc_v,'),
    ln(b'        const int n_mc,'),
    ln(b'        const galosh_yuv_params_t *params)'),
    ln(b'{'),
    ln(b'    if(!params) params = &GALOSH_YUV_DEFAULTS;'),
    ln(b'    init_galosh_kaiser();'),
    NL,
    ln(b'    /* Chroma plane dimensions */'),
    ln(b'    const int cw = (params->yuv_format == GALOSH_YUV_420) ? width  / 2 : width;'),
    ln(b'    const int ch = (params->yuv_format == GALOSH_YUV_420) ? height / 2 : height;'),
    NL,
    ln(b'    fprintf(stderr, "[yuv_galosh] %dx%d YUV%d  tr=%d  sy=%.2f sc=%.2f"'),
    ln(b'                    " stride_y=%d stride_c=%d  gamma=%.2f\\n",'),
    ln(b'            width, height, params->yuv_format, params->tr,'),
    ln(b'            params->sigma_y, params->sigma_c,'),
    ln(b'            params->stride_y, params->stride_c,'),
    ln(b'            params->gamma_curve);'),
    NL,
    ln(b'    /* Gamma pipeline: GAT requires linear (photon-count) domain.'),
    ln(b'     * gamma_curve > 1.0 => linearise input, denoise, re-apply gamma. */'),
    ln(b'    const float gc        = params->gamma_curve;'),
    ln(b'    const int   use_gamma = (gc > 1.0f + 1e-3f);'),
    NL,
    ln(b'    const size_t y_npix = (size_t)width * height;'),
    ln(b'    const size_t c_npix = (size_t)cw    * ch;'),
    NL,
    ln(b'    float *y_lin = NULL, *u_lin = NULL, *v_lin = NULL;'),
    ln(b'    float **mc_y_lin = NULL, **mc_u_lin = NULL, **mc_v_lin = NULL;'),
    NL,
    ln(b'    if(use_gamma)'),
    ln(b'    {'),
    ln(b'        y_lin = plane_linearize(y_in, (int)y_npix, gc);'),
    ln(b'        u_lin = plane_linearize(u_in, (int)c_npix, gc);'),
    ln(b'        v_lin = plane_linearize(v_in, (int)c_npix, gc);'),
    ln(b'        if(!y_lin || !u_lin || !v_lin)'),
    ln(b'        {'),
    ln(b'            fprintf(stderr, "[yuv_galosh] alloc failed in gamma linearise\\n");'),
    ln(b'            dt_free_align(y_lin); dt_free_align(u_lin); dt_free_align(v_lin);'),
    ln(b'            return -1;'),
    ln(b'        }'),
    ln(b'        if(n_mc > 0)'),
    ln(b'        {'),
    ln(b'            mc_y_lin = calloc(n_mc, sizeof(float *));'),
    ln(b'            mc_u_lin = calloc(n_mc, sizeof(float *));'),
    ln(b'            mc_v_lin = calloc(n_mc, sizeof(float *));'),
    ln(b'            for(int fi = 0; fi < n_mc; fi++)'),
    ln(b'            {'),
    ln(b'                if(mc_y && mc_y[fi]) mc_y_lin[fi] = plane_linearize(mc_y[fi], (int)y_npix, gc);'),
    ln(b'                if(mc_u && mc_u[fi]) mc_u_lin[fi] = plane_linearize(mc_u[fi], (int)c_npix, gc);'),
    ln(b'                if(mc_v && mc_v[fi]) mc_v_lin[fi] = plane_linearize(mc_v[fi], (int)c_npix, gc);'),
    ln(b'            }'),
    ln(b'        }'),
    ln(b'    }'),
    NL,
    ln(b'    const float *y_src       = use_gamma ? y_lin : y_in;'),
    ln(b'    const float *u_src       = use_gamma ? u_lin : u_in;'),
    ln(b'    const float *v_src       = use_gamma ? v_lin : v_in;'),
    ln(b'    const float * const *mcy = (use_gamma && mc_y_lin) ? (const float * const *)mc_y_lin : mc_y;'),
    ln(b'    const float * const *mcu = (use_gamma && mc_u_lin) ? (const float * const *)mc_u_lin : mc_u;'),
    ln(b'    const float * const *mcv = (use_gamma && mc_v_lin) ? (const float * const *)mc_v_lin : mc_v;'),
    NL,
    ln(b'    const float gc_est = use_gamma ? 1.0f : gc;'),
    ln(b'    const galosh_noise_t np_y = galosh_estimate_noise_plane(y_src, width, height, 1, gc_est);'),
    ln(b'    const galosh_noise_t np_u = galosh_estimate_noise_plane(u_src, cw,    ch,    0, gc_est);'),
    ln(b'    const galosh_noise_t np_v = galosh_estimate_noise_plane(v_src, cw,    ch,    0, gc_est);'),
    NL,
    ln(b'    fprintf(stderr, "[yuv_galosh] noise  Y: alpha=%.2e sigma_sq=%.2e  %s\\n",'),
    ln(b'            np_y.alpha, np_y.sigma_sq,'),
    ln(b'            np_y.alpha >= GAT_ALPHA_THRESHOLD ? "-> full PG GAT" : "-> Gaussian GAT");'),
    ln(b'    fprintf(stderr, "[yuv_galosh] noise  U: alpha=%.2e sigma_sq=%.2e  -> Gaussian GAT\\n",'),
    ln(b'            np_u.alpha, np_u.sigma_sq);'),
    ln(b'    fprintf(stderr, "[yuv_galosh] noise  V: alpha=%.2e sigma_sq=%.2e  -> Gaussian GAT\\n",'),
    ln(b'            np_v.alpha, np_v.sigma_sq);'),
    NL,
    ln(b'    fprintf(stderr, "[yuv_galosh] Processing Y plane...\\n");'),
    ln(b'    galosh_yuv_denoise_plane(y_src, y_out, width, height,'),
    ln(b'                              params->sigma_y, params->stride_y,'),
    ln(b'                              np_y, mcy, n_mc);'),
    ln(b'    if(use_gamma) plane_apply_gamma_inplace(y_out, (int)y_npix, gc);'),
    NL,
    ln(b'    fprintf(stderr, "[yuv_galosh] Processing U plane...\\n");'),
    ln(b'    galosh_yuv_denoise_plane(u_src, u_out, cw, ch,'),
    ln(b'                              params->sigma_c, params->stride_c,'),
    ln(b'                              np_u, mcu, n_mc);'),
    ln(b'    if(use_gamma) plane_apply_gamma_inplace(u_out, (int)c_npix, gc);'),
    NL,
    ln(b'    fprintf(stderr, "[yuv_galosh] Processing V plane...\\n");'),
    ln(b'    galosh_yuv_denoise_plane(v_src, v_out, cw, ch,'),
    ln(b'                              params->sigma_c, params->stride_c,'),
    ln(b'                              np_v, mcv, n_mc);'),
    ln(b'    if(use_gamma) plane_apply_gamma_inplace(v_out, (int)c_npix, gc);'),
    NL,
    ln(b'    if(use_gamma)'),
    ln(b'    {'),
    ln(b'        dt_free_align(y_lin); dt_free_align(u_lin); dt_free_align(v_lin);'),
    ln(b'        if(mc_y_lin) { for(int fi=0;fi<n_mc;fi++) dt_free_align(mc_y_lin[fi]); free(mc_y_lin); }'),
    ln(b'        if(mc_u_lin) { for(int fi=0;fi<n_mc;fi++) dt_free_align(mc_u_lin[fi]); free(mc_u_lin); }'),
    ln(b'        if(mc_v_lin) { for(int fi=0;fi<n_mc;fi++) dt_free_align(mc_v_lin[fi]); free(mc_v_lin); }'),
    ln(b'    }'),
    NL,
    ln(b'    fprintf(stderr, "[yuv_galosh] Done.\\n");'),
    ln(b'    return 0;'),
    ln(b'}'),
    NL,
])

# ---- Standalone test harness (main) ----
HARNESS = b''.join([
    ln(b'/* ================================================================'),
    ln(b' * Standalone test harness'),
    ln(b' *'),
    ln(b' * Input file: raw planar float32 YUV'),
    ln(b' *   Layout: Y[H*W] U[cH*cW] V[cH*cW]  (float32, native endian)'),
    ln(b' * Output file: same format.'),
    ln(b' * ================================================================ */'),
    ln(b'#ifdef GALOSH_STANDALONE'),
    ln(b'int main(int argc, char **argv)'),
    ln(b'{'),
    ln(b'    if(argc < 5)'),
    ln(b'    {'),
    ln(b'        fprintf(stderr,'),
    ln(b'            "Usage: %s in.yuv out.yuv W H [fmt] [sy] [sc] [stride_y] [stride_c] [gamma] [mc*.yuv ...]\\n"'),
    ln(b'            "  fmt       420 or 444 (default 420)\\n"'),
    ln(b'            "  sy        Y  denoising strength (default 1.0)\\n"'),
    ln(b'            "  sc        UV denoising strength (default 1.0)\\n"'),
    ln(b'            "  stride_y  Y  block stride 2=75%% overlap, 4=50%% (default 2)\\n"'),
    ln(b'            "  stride_c  UV block stride (default 2)\\n"'),
    ln(b'            "  gamma     display gamma for alpha estimation: 1.0=linear RAW (default),\\n"'),
    ln(b'            "            2.2=sRGB approx.  Compensates variance-mean regression so that\\n"'),
    ln(b'            "            Poisson alpha is correctly estimated in gamma-compressed input.\\n"'),
    ln(b'            "  mc*.yuv   motion-compensated frames for 3D mode\\n",'),
    ln(b'            argv[0]);'),
    ln(b'        return 1;'),
    ln(b'    }'),
    NL,
    ln(b'    const char *fin  = argv[1];'),
    ln(b'    const char *fout = argv[2];'),
    ln(b'    const int width  = atoi(argv[3]);'),
    ln(b'    const int height = atoi(argv[4]);'),
    ln(b'    if(width <= 0 || height <= 0)'),
    ln(b'    { fprintf(stderr, "Bad dimensions\\n"); return 1; }'),
    NL,
    ln(b'    galosh_yuv_params_t p = GALOSH_YUV_DEFAULTS;'),
    ln(b'    if(argc > 5)  p.yuv_format  = atoi(argv[5]);'),
    ln(b'    if(argc > 6)  p.sigma_y     = (float)atof(argv[6]);'),
    ln(b'    if(argc > 7)  p.sigma_c     = (float)atof(argv[7]);'),
    ln(b'    if(argc > 8)  p.stride_y    = atoi(argv[8]);'),
    ln(b'    if(argc > 9)  p.stride_c    = atoi(argv[9]);'),
    ln(b'    if(argc > 10) p.gamma_curve = (float)atof(argv[10]);'),
    NL,
    ln(b'    const int cw = (p.yuv_format == GALOSH_YUV_420) ? width  / 2 : width;'),
    ln(b'    const int ch = (p.yuv_format == GALOSH_YUV_420) ? height / 2 : height;'),
    ln(b'    const size_t y_npix      = (size_t)width  * height;'),
    ln(b'    const size_t c_npix      = (size_t)cw     * ch;'),
    ln(b'    const size_t frame_floats = y_npix + 2 * c_npix;'),
    ln(b'    const size_t frame_bytes  = frame_floats * sizeof(float);'),
    NL,
    ln(b'    float *buf_in = dt_alloc_align_float(frame_floats);'),
    ln(b'    if(!buf_in) { fprintf(stderr, "alloc failed\\n"); return 1; }'),
    ln(b'    {'),
    ln(b'        FILE *fi = fopen(fin, "rb");'),
    ln(b'        if(!fi) { fprintf(stderr, "Cannot open %s\\n", fin); return 1; }'),
    ln(b'        if(fread(buf_in, 1, frame_bytes, fi) != frame_bytes)'),
    ln(b'            fprintf(stderr, "Warning: short read on %s\\n", fin);'),
    ln(b'        fclose(fi);'),
    ln(b'    }'),
    NL,
    ln(b'    const float *y_in = buf_in;'),
    ln(b'    const float *u_in = buf_in + y_npix;'),
    ln(b'    const float *v_in = buf_in + y_npix + c_npix;'),
    NL,
    ln(b'    /* Optional MC frames */'),
    ln(b'    const int mc_arg_start = 11;'),
    ln(b'    const int n_mc = MAX(0, argc - mc_arg_start);'),
    ln(b'    p.tr = n_mc / 2;'),
    ln(b'    float        **mc_buf   = (float **)calloc(MAX(n_mc,1), sizeof(float *));'),
    ln(b'    const float **mc_y_arr  = (const float **)calloc(MAX(n_mc,1), sizeof(float *));'),
    ln(b'    const float **mc_u_arr  = (const float **)calloc(MAX(n_mc,1), sizeof(float *));'),
    ln(b'    const float **mc_v_arr  = (const float **)calloc(MAX(n_mc,1), sizeof(float *));'),
    ln(b'    for(int i = 0; i < n_mc; i++)'),
    ln(b'    {'),
    ln(b'        mc_buf[i] = dt_alloc_align_float(frame_floats);'),
    ln(b'        if(!mc_buf[i]) { fprintf(stderr, "alloc failed\\n"); return 1; }'),
    ln(b'        FILE *mf = fopen(argv[mc_arg_start + i], "rb");'),
    ln(b'        if(!mf) { fprintf(stderr, "Cannot open %s\\n", argv[mc_arg_start+i]); return 1; }'),
    ln(b'        if(fread(mc_buf[i], 1, frame_bytes, mf) != frame_bytes)'),
    ln(b'            fprintf(stderr, "Warning: short read on MC frame %d\\n", i);'),
    ln(b'        fclose(mf);'),
    ln(b'        mc_y_arr[i] = mc_buf[i];'),
    ln(b'        mc_u_arr[i] = mc_buf[i] + y_npix;'),
    ln(b'        mc_v_arr[i] = mc_buf[i] + y_npix + c_npix;'),
    ln(b'    }'),
    ln(b'    if(n_mc > 0)'),
    ln(b'        fprintf(stderr, "[yuv_galosh] 3D mode: n_mc=%d tr=%d\\n", n_mc, p.tr);'),
    NL,
    ln(b'    float *buf_out = dt_alloc_align_float(frame_floats);'),
    ln(b'    if(!buf_out) { fprintf(stderr, "alloc failed\\n"); return 1; }'),
    ln(b'    float *y_out = buf_out;'),
    ln(b'    float *u_out = buf_out + y_npix;'),
    ln(b'    float *v_out = buf_out + y_npix + c_npix;'),
    NL,
    ln(b'    int ret = galosh_yuv_denoise(y_out, u_out, v_out,'),
    ln(b'                                  y_in,  u_in,  v_in,'),
    ln(b'                                  width, height,'),
    ln(b'                                  mc_y_arr, mc_u_arr, mc_v_arr, n_mc, &p);'),
    ln(b'    if(ret != 0) { fprintf(stderr, "galosh_yuv_denoise failed\\n"); return 1; }'),
    NL,
    ln(b'    {'),
    ln(b'        FILE *fo = fopen(fout, "wb");'),
    ln(b'        if(!fo) { fprintf(stderr, "Cannot open %s for write\\n", fout); return 1; }'),
    ln(b'        fwrite(buf_out, 1, frame_bytes, fo);'),
    ln(b'        fclose(fo);'),
    ln(b'    }'),
    NL,
    ln(b'    for(int i = 0; i < n_mc; i++) dt_free_align(mc_buf[i]);'),
    ln(b'    free(mc_buf); free(mc_y_arr); free(mc_u_arr); free(mc_v_arr);'),
    ln(b'    dt_free_align(buf_in);'),
    ln(b'    dt_free_align(buf_out);'),
    ln(b'    return 0;'),
    ln(b'}'),
    ln(b'#endif /* GALOSH_STANDALONE */'),
])

result = prefix + FUNC + HARNESS
with open(SRC, 'wb') as f:
    f.write(result)

n = result.count(b'int galosh_yuv_denoise(')
print(f'Written {len(result)} bytes. galosh_yuv_denoise count: {n}')